- README.md
- cloudsmith/provider.go
- cloudsmith/resource_entitlement.go
- cloudsmith/resource_entitlement_test.go
- go.mod
- go.sum
This PR adds a basic entitlement resource, allowing management of entitlement tokens within a repository.
> Add basic entitlement resource

- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE.md
- .github/SUPPORT.md
This PR adds a number of files that are common to all of the official providers.
> Add templates (CoC, issue template, etc) that are common to all providers

- README.md
This PR adds basic build and test details to the README (removing the TODO sections).
> Add build and test details to README

- .github/workflows/acceptance-tests.yml
Adds slack notifications to workflow runs on success/fail.
> Add slack notifications to workflow run

- docs/data-sources/repository.md
Adds all exported fields to repository data source docs.
> fix: add fields to docs for repository data source

- cloudsmith/resource_repository_geo_ip_rules.go
- go.mod
- go.sum
Update to the latest version of the Cloudsmith API bindings.
> fix: update to v0.0.22 of the Cloudsmith go bindings

- cloudsmith/resource_service.go
- cloudsmith/resource_service_test.go
This PR allows service team assignments to be updated now that the API has been fixed.
Fixes #39
> fix: allow service team assignments to be changed

- cloudsmith/provider.go
- cloudsmith/resource_license_policy.go
- cloudsmith/resource_vulnerability_policy.go
- cloudsmith/resource_vulnerability_policy_test.go
- docs/resources/vulnerability_policy.md
This PR adds a `cloudsmith_vulnerability_policy` resource to allow creation and management of organization vulnerability policies with Terraform.
> feat(eng-2245): Vulnerability policy resource

- cloudsmith/resource_repository_geo_ip_rules.go
- go.mod
- go.sum
Update to api bindings v0.0.26
> fix: Update to api bindings v0.0.26

- go.mod
- go.sum
Update to api bindings v0.0.28
> fix: update to api bindings v0.0.28

- docs/data-sources/package.md
Update `package` data_resource documentation
> Update package documentation

- cloudsmith/data_source_package.go
- docs/data-sources/package.md
Add checksum attributes to package data resource
> NO-TICKET: Add checksum attribute to package resource

- go.mod
- go.sum
update to api bindings v0.0.29
> fix: update to api bindings v0.0.29

- docs/resources/service.md
Updates to reflect the behaviour of the previously released flag.
> NO-TICKET: Updated service docs

- cloudsmith/data_source_repository_privileges.go
- cloudsmith/data_source_repository_privileges_test.go
- cloudsmith/provider.go
- cloudsmith/resource_repository_privileges.go
- docs/data-sources/repository_privileges.md
Add support for reading repo privileges.
> NO-TICKET: Data source for repo privileges 

- cloudsmith/resource_service.go
In version 0.0.28 we have introduced `store_api_key` option in the service module which unexpectedly overwrites any existing terraform states API keys with `**redacted**` as the logic wasn't there to handle the change. 
This fix checks if the API key exists in the state and also makes sure that `store_api_key` is set to `False` before overwriting the value on existing runs, any new runs will work as intended.
> FIX: Don't overwrite current service api key

- cloudsmith/resource_service.go
This is a patch that was introduced in v0.0.28 where any terraform states on older version would get their service account API keys set to `**redacted**` as it was trying to update an existing object and there was no logic to prevent an overwrite. This change prevents this unless a user explicitly sets `store_api_key` to `false`.
> FIX: Don't overwrite current API keys with new `store_api_key` flag

- cloudsmith/provider.go
- cloudsmith/resource_oidc.go
- cloudsmith/resource_oidc_test.go
- docs/resources/oidc.md
- go.mod
- go.sum
Add OIDC Resource to the terraform provider.
> CENG-55: Add OIDC Resource

- cloudsmith/data_entitlement.go
- cloudsmith/data_entitlement_test.go
- cloudsmith/provider.go
- docs/data-sources/entitlement_list.md
Add the ability to pull entitlement tokens from a data source
> CENG-104: add entitlement_list data resource

- docs/resources/repository.md
- examples/flat-example/README.md
- examples/flat-example/global-variables.tf
- examples/flat-example/org-license-policy.tf
- examples/flat-example/org-oidc-config.tf
- examples/flat-example/org-saml-group.tf
- examples/flat-example/org-services.tf
- examples/flat-example/org-teams.tf
- examples/flat-example/org-vulnerability-policy.tf
- examples/flat-example/repo-devops.tf
- examples/flat-example/repo-oidc-demo.tf
- examples/flat-example/repo-staging.tf
- examples/flat-example/repo-upstreams.tf
Add a basic template/starter/demo code
> Add example terraform code

- docs/resources/team_manage.md
> chore: update manage team docs

- .github/workflows/release.yml
- cloudsmith/resource_webhook_test.go
Update go release to latest version and use a new flag for distro clean
> chore(update release workflow)

- .github/workflows/release.yml
- .goreleaser.yml
Update release yml version to v2
> Chore(Update releaser file)

- .goreleaser.yml
- docs/resources/manage_team.md
* Update docs
* Rename doc filename
* Update release.yml to use new update value for skipping changelog
> path(small-fixes)

- cloudsmith/resource_repository_upstream_test.go
* Update upstream test to reflect new changes
> CENG-252: Update upstream tests to reflect new API changes

- cloudsmith/data_source_organization_members.go
- cloudsmith/data_source_organization_members_test.go
- cloudsmith/provider.go
- cloudsmith/resource_repository_upstream_test.go
- docs/data-sources/organization_list_org_memebrs.md
Adds the ability to retrieve the full list of organisation members within Cloudsmith.
> CENG-276: List all org users data source

- cloudsmith/data_source_organization_member_details.go
- cloudsmith/data_source_organization_member_details_test.go
- cloudsmith/provider.go
- docs/data-sources/organization_list_org_memebrs.md
- docs/data-sources/organization_member_details.md
* Adds a data source to grab specific user details as per our [API](https://help.cloudsmith.io/reference/orgs_members_read)
> CENG-279: Member details data source

- cloudsmith/resource_repository_retention_rule.go
This PR fixes the retention rule limits, allowing the user to set them to `0`, which marks it as `disabled` in the UI. This previously wasn't working correctly because Golang treated 0 as an empty value in the struct and sent over invalid JSON values.
> PATCH: Fix retention rule limit to allow 0 value to be correctly passed

- cloudsmith/provider.go
- cloudsmith/resource_saml_auth.go
- cloudsmith/resource_saml_auth_test.go
- docs/resources/saml_auth.md
This enables the terraform provider to configure saml authorisation on an organisation.
> feat(ENG-6470): add support for configuring saml authentication
