cloudsmith-io/terraform-provider-cloudsmith

.github/workflows/acceptance-tests.yml
This PR adds a Github Actions config to run acceptance tests on every PR to master and on an overnight schedule to ensure the provider continues to work as expected.
=> Add basic acceptance testing in Github actions

.github/workflows/release.yml, .goreleaser.yml
This PR adds a workflow for triggering new (draft) releases on tag push.
=> Add workflow and configuration for running goreleaser on new tags

docs/data-sources/namespace.md, docs/index.md, docs/resources/entitlement.md, docs/resources/repository.md
This PR adds basic documentation required for display in the Terraform registry (with links back to help.cloudsmith.io).
=> Add basic documentation for display in Terraform registry

README.md, cloudsmith/data_source_packages.go, cloudsmith/data_source_repository.go, cloudsmith/provider.go, go.mod, go.sum
This datasource can be used to retrieve packages from Cloudsmith for a given Namespace and Repository. I have implemented a paging handler as I was surprised by the behaviour of the PackageList API call. I have also implemented filters and their usage is encouraged, to avoid repeated calls/large datasets. 
The version of the Cloudsmith Go API library is out of date. The provider did not work as the API now returns an integer for the Package.Stage value. The library version that was in-use expected a string.
=> Add a datasource for retrieving repositories and packages from Cloudsmith

README.md, cloudsmith/data_source_package_list.go, cloudsmith/data_source_repository.go, cloudsmith/provider.go, docs/data-sources/package_list.md, docs/data-sources/repository.md
* Added documentation to the `Repository` and `PackageList` data sources.
* Made `cloudsmith_repository` consume `identifier` rather than `name`
* Fixes for data source schema integrity (inputs vs outputs)
* Renamed `cloudsmith_packages` to `cloudsmith_package_list`
* Removed `package_group` from the packages data source, this can be specified via `filters` more explicitly.
=> Added Repository and Packages Data Source Docs + Tweaks

.github/workflows/release.yml, .goreleaser.yml
* Added an 'import GPG key' step to the goreleaser workflow
* Added a signature artifact to the goreleaser output, as per https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-
=> NO-TICKET: Add GPG signed checksums to goreleaser

.github/workflows/acceptance-tests.yml, .github/workflows/release.yml, go.mod, go.sum
This PR upgrades the provider to Go 1.18 to enable support for new platforms (Darwin/Arm64 mostly).
=> fix: upgrade to Go 1.18 to enable support for new platforms

cloudsmith/data_source_repository.go, cloudsmith/data_source_repository_test.go
This PR extends the `repository` data source to expose all relevant fields from the API. Those that are missing are either not relevant for Terraform (please open an issue if you notice any you'd like added) or going to be added as standalone data sources/resources in follow up PRs.
=> feat: extend repository data source to include all exposed fields

cloudsmith/provider.go, cloudsmith/resource_team.go, cloudsmith/resource_team_test.go, docs/resources/team.md
This PR adds a new `cloudsmith_team` resource to allow managing teams for an organization.
=> feat: add cloudsmith_team resource

cloudsmith/provider.go, cloudsmith/resource_service.go, cloudsmith/resource_service_test.go, docs/resources/service.md, go.mod
This PR adds a new `cloudsmith_service` resource to allow managing services (service accounts/bots) for an organization.
=> feat: add service resource

cloudsmith/data_source_namespace.go, docs/data-sources/namespace.md, docs/data-sources/repository.md, docs/resources/entitlement.md, docs/resources/repository.md, docs/resources/webhook.md
This PR deprecates the `cloudsmith_namespace` data source in favor of the newer `cloudsmith_organization` data source.
The existing resource will continue to work, but will be removed in future once `namespace` is fully removed from the cloudsmith API and website.
=> fix: deprecate cloudsmith_namespace data source

cloudsmith/provider.go, cloudsmith/resource_repository_privileges.go, cloudsmith/resource_repository_privileges_test.go, cloudsmith/utils.go, docs/resources/repository_privileges.md
This PR adds a new `cloudsmith_repository_privileges` resource to allow managing privileges/permissions (service accounts, teams, and users) for a repository.
=> feat: add cloudsmith_repository_privileges resource

.gitignore, cloudsmith/provider.go, cloudsmith/resource_repository_geo_ip_rules.go, cloudsmith/resource_repository_geo_ip_rules_test.go, cloudsmith/utils.go, docs/resources/repository_geo_ip_rules.md, go.mod, go.sum
Adds a new `cloudsmith_repository_geo_ip_rules` resource to allow managing Geo/IP restrictions for a repository.
=> feat: add repo geo/ip rules resource

cloudsmith/resource_repository_geo_ip_rules.go, cloudsmith/utils.go
Adds checks and a wait to ensure that mutating operations on Repository Geo/IP rules don't return until data has been replicated.
=> fix(eng-1866): Add waits to geo/ip mutations

cloudsmith/resource_entitlement.go, cloudsmith/resource_entitlement_test.go, cloudsmith/resource_repository.go, cloudsmith/resource_repository_geo_ip_rules.go, cloudsmith/resource_repository_geo_ip_rules_test.go, cloudsmith/resource_repository_privileges.go, cloudsmith/resource_repository_privileges_test.go, cloudsmith/resource_repository_test.go, cloudsmith/resource_service.go, cloudsmith/resource_service_test.go, cloudsmith/resource_team.go, cloudsmith/resource_team_test.go, cloudsmith/resource_webhook.go, cloudsmith/resource_webhook_test.go, docs/resources/entitlement.md, docs/resources/repository.md, docs/resources/repository_geo_ip_rules.md, docs/resources/repository_privileges.md, docs/resources/service.md, docs/resources/team.md, docs/resources/webhook.md
This PR adds the ability to `terraform import` all available resources. This functionality is crucial for users migrating existing resources into Terraform as we expand the provider.
=> feat: add ability to import all resources

cloudsmith/resource_license_policy.go, cloudsmith/resource_license_policy_test.go, cloudsmith/resource_vulnerability_policy.go, cloudsmith/resource_vulnerability_policy_test.go, docs/resources/license_policy.md, docs/resources/vulnerability_policy.md, go.mod, go.sum
This PR adds the `policy_query_string` option to `cloudsmith_license_policy` and `cloudsmith_vulnerability_policy` resources to target specific packages to apply to polices with Terraform.
=> feat(eng-2375): Add package_query_string to policies

cloudsmith/resource_service.go, cloudsmith/resource_service_test.go, docs/resources/service.md
Context:
We are currently returning the service account API key to state which causes warnings when rotating the keys outside of the state. The aim of this PR is to provide the option to not return the API key at all which provides additional security and suppresses the warnings as it defaults the "key" value to "disabled"
=> Add optional flag to disable api key return

cloudsmith/data_source_package.go, cloudsmith/data_source_package_test.go, docs/data-sources/package.md
Previously, we were grabbing the package checksum via our API which meant that the checksum could be out-of-sync whenever a package is re-published due to caching. This commit ensures that the checksums that are being returned are from the downloaded package and when the package is not downloaded, the checksums will then be returned from the API.
=> PRO-752: Calculate package checksum locally when downloaded

examples/flat-example/org-deny-policy.tf, examples/flat-example/provider.tf, examples/iterative-example/README.md, examples/iterative-example/global-variables.tf, examples/iterative-example/license-policy.tf, examples/iterative-example/oidc-config.tf, examples/iterative-example/provider.tf, examples/iterative-example/repositories.tf, examples/iterative-example/services.tf, examples/iterative-example/teams.tf, examples/iterative-example/terraform.tfvars, examples/iterative-example/upstreams.tf, examples/iterative-example/vulnerability-policy.tf
Added in a provider.tf to the flat-example so that it is immediately runnable after modifying the global-variables.tf with an organization name and API key. Also added an example module for the package deny policy resource.
Provided an example project creating many similar repositories using for_each and dynamically updating resources based off of a terraform.tfvars configuration.
=> Update flat-example and add iterative-example

docs/resources/service.md
Fixing [issue 74](https://github.com/cloudsmith-io/terraform-provider-cloudsmith/issues/74). 
* Service account referenced `slug_perm` in examples whilst the API only allows `slug` for the service endpoint, this PR changes that example to correct use of `slug`.
=> CENG-272: Update service resource docs

.github/workflows/release.yml
The release workflow now requires `permissions` to be passed in order to interact with the repository contents.
=> Chore(Update workflow permissions)

cloudsmith/resource_package_deny_policy.go, cloudsmith/resource_package_deny_policy_test.go, cloudsmith/resource_repository.go, docs/data-sources/entitlement_list.md, docs/resources/package_deny_policy.md
Adding PR review fixes based on community PRs from @noelgass and @RoseSecurity
=> CENG-286: PR reviews

cloudsmith/resource_repository.go, docs/resources/repository.md
* Removed North California from `region_type` as this region has been [deprecated](https://changelog.cloudsmith.com/en/deprecating-the-northern-california-storage-region?user_id=996da31c-0dfb-4f58-99ed-35d3e5276e0b).
=> CENG-305: Remove NorCal from docs

cloudsmith/resource_repository.go, docs/resources/repository.md
* Update repo docs to reflect `name` behaviour around whitespaces
* Update repo docs example - removed whitespace
* Added back `default` region to validation function in repository resource
=> CENG-333: Update repo docs

cloudsmith/provider.go, cloudsmith/provider_config.go
When attempting to query internal cloudsmith APIs authentication issues were faced due to needing additional headers.
=> Allow for arbitrary headers

.gitignore, cloudsmith/resource_saml_auth.go
When attempting to import a SAML auth provider where no URL was specified I faced a nil pointer issue. Looking at the code this makes sense.
This commit is to fix that by doing null checks.
=> fix(no-ticket): fix  null pointer issues on saml resource

cloudsmith/resource_repository_upstream.go, cloudsmith/resource_repository_upstream_test.go, docs/resources/repository_upstream.md
The most recent release requires the user to pass a path to the cert/key for upstream authentication, this change utilises the `file()` function provided by terraform which improves this process.
=> No-ticket: Update the cert and key auth to be more robust
